// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: prod/raftrpc/raft.proto

package raftrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope carries one raft.RPCMessage. payload is the JSON encoding of
// whichever concrete Go struct (RequestVoteArgs, AppendEntriesReply, etc.)
// `type` says it is - JSON here rather than a protobuf oneof so the wire
// encoding of a Raft RPC's payload is identical across all three
// transports (sim, Maelstrom, gRPC) this repo has; only the delivery
// mechanism changes. If Payload's structure ever needs stronger schema
// guarantees than that, a oneof of dedicated messages here is the natural
// upgrade path, and it's isolated to this one file.
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Term          int64                  `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_prod_raftrpc_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_prod_raftrpc_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_prod_raftrpc_raft_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Envelope) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Envelope) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Envelope) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_prod_raftrpc_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_prod_raftrpc_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_prod_raftrpc_raft_proto_rawDescGZIP(), []int{1}
}

var File_prod_raftrpc_raft_proto protoreflect.FileDescriptor

var file_prod_raftrpc_raft_proto_rawDesc = string([]byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x64, 0x2f, 0x72, 0x61, 0x66, 0x74, 0x72, 0x70, 0x63, 0x2f, 0x72,
	0x61, 0x66, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72, 0x61, 0x66, 0x74, 0x72,
	0x70, 0x63, 0x22, 0x70, 0x0a, 0x08, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x22, 0x05, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x32, 0x38, 0x0a, 0x0d, 0x52,
	0x61, 0x66, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x27, 0x0a, 0x04,
	0x53, 0x65, 0x6e, 0x64, 0x12, 0x11, 0x2e, 0x72, 0x61, 0x66, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x45,
	0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x1a, 0x0c, 0x2e, 0x72, 0x61, 0x66, 0x74, 0x72, 0x70,
	0x63, 0x2e, 0x41, 0x63, 0x6b, 0x42, 0x16, 0x5a, 0x14, 0x72, 0x61, 0x66, 0x74, 0x2d, 0x6b, 0x76,
	0x2f, 0x70, 0x72, 0x6f, 0x64, 0x2f, 0x72, 0x61, 0x66, 0x74, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_prod_raftrpc_raft_proto_rawDescOnce sync.Once
	file_prod_raftrpc_raft_proto_rawDescData []byte
)

func file_prod_raftrpc_raft_proto_rawDescGZIP() []byte {
	file_prod_raftrpc_raft_proto_rawDescOnce.Do(func() {
		file_prod_raftrpc_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_prod_raftrpc_raft_proto_rawDesc), len(file_prod_raftrpc_raft_proto_rawDesc)))
	})
	return file_prod_raftrpc_raft_proto_rawDescData
}

var file_prod_raftrpc_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_prod_raftrpc_raft_proto_goTypes = []any{
	(*Envelope)(nil), // 0: raftrpc.Envelope
	(*Ack)(nil),      // 1: raftrpc.Ack
}
var file_prod_raftrpc_raft_proto_depIdxs = []int32{
	0, // 0: raftrpc.RaftTransport.Send:input_type -> raftrpc.Envelope
	1, // 1: raftrpc.RaftTransport.Send:output_type -> raftrpc.Ack
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_prod_raftrpc_raft_proto_init() }
func file_prod_raftrpc_raft_proto_init() {
	if File_prod_raftrpc_raft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_prod_raftrpc_raft_proto_rawDesc), len(file_prod_raftrpc_raft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prod_raftrpc_raft_proto_goTypes,
		DependencyIndexes: file_prod_raftrpc_raft_proto_depIdxs,
		MessageInfos:      file_prod_raftrpc_raft_proto_msgTypes,
	}.Build()
	File_prod_raftrpc_raft_proto = out.File
	file_prod_raftrpc_raft_proto_goTypes = nil
	file_prod_raftrpc_raft_proto_depIdxs = nil
}