// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: prod/raftrpc/raft.proto

package raftrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RaftTransport_Send_FullMethodName = "/raftrpc.RaftTransport/Send"
)

// RaftTransportClient is the client API for RaftTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RaftTransport is deliberately one fire-and-forget method, not one RPC per
// Raft message type (RequestVote, AppendEntries, ...). raft.Network's own
// contract (raft/interfaces.go) is asymmetric: Send delivers a message and
// returns only an error, never a reply value - a RequestVote's reply comes
// back later as an independent RequestVoteReply message sent the other
// direction (raft/node.go's HandleMessage does this explicitly). Modeling
// this RPC as synchronous request/response would fight that contract
// instead of implementing it; Envelope.type plus a shared decode-by-type
// step (grpc_transport.go, mirroring maelstrom/network.go's
// decodeRPCPayload) is what actually matches how every other transport in
// this repo (sim.Network, maelstrom.NetworkAdapter) already works.
type RaftTransportClient interface {
	Send(ctx context.Context, in *Envelope, opts ...grpc.CallOption) (*Ack, error)
}

type raftTransportClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftTransportClient(cc grpc.ClientConnInterface) RaftTransportClient {
	return &raftTransportClient{cc}
}

func (c *raftTransportClient) Send(ctx context.Context, in *Envelope, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, RaftTransport_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftTransportServer is the server API for RaftTransport service.
// All implementations must embed UnimplementedRaftTransportServer
// for forward compatibility.
//
// RaftTransport is deliberately one fire-and-forget method, not one RPC per
// Raft message type (RequestVote, AppendEntries, ...). raft.Network's own
// contract (raft/interfaces.go) is asymmetric: Send delivers a message and
// returns only an error, never a reply value - a RequestVote's reply comes
// back later as an independent RequestVoteReply message sent the other
// direction (raft/node.go's HandleMessage does this explicitly). Modeling
// this RPC as synchronous request/response would fight that contract
// instead of implementing it; Envelope.type plus a shared decode-by-type
// step (grpc_transport.go, mirroring maelstrom/network.go's
// decodeRPCPayload) is what actually matches how every other transport in
// this repo (sim.Network, maelstrom.NetworkAdapter) already works.
type RaftTransportServer interface {
	Send(context.Context, *Envelope) (*Ack, error)
	mustEmbedUnimplementedRaftTransportServer()
}

// UnimplementedRaftTransportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRaftTransportServer struct{}

func (UnimplementedRaftTransportServer) Send(context.Context, *Envelope) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedRaftTransportServer) mustEmbedUnimplementedRaftTransportServer() {}
func (UnimplementedRaftTransportServer) testEmbeddedByValue()                       {}

// UnsafeRaftTransportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftTransportServer will
// result in compilation errors.
type UnsafeRaftTransportServer interface {
	mustEmbedUnimplementedRaftTransportServer()
}

func RegisterRaftTransportServer(s grpc.ServiceRegistrar, srv RaftTransportServer) {
	// If the following call panics, it indicates UnimplementedRaftTransportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RaftTransport_ServiceDesc, srv)
}

func _RaftTransport_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Envelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftTransportServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftTransport_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftTransportServer).Send(ctx, req.(*Envelope))
	}
	return interceptor(ctx, in, info, handler)
}

// RaftTransport_ServiceDesc is the grpc.ServiceDesc for RaftTransport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftTransport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "raftrpc.RaftTransport",
	HandlerType: (*RaftTransportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _RaftTransport_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "prod/raftrpc/raft.proto",
}